sudo: false
language: node_js
node_js:
  - "10.15.1"
branches:
  only:
    - develop
cache:
  directories:
    - "$HOME/.npm"
# before_install:
#   - npm update
install:
  - npm ci
script:
  - npm run test
after_success:
  - npm run coveralls
